<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <UserSecretsId>aefa38f9-375a-46f3-8107-2570034c62e7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configurations\20220829100113_addPictureColumnToıTEM.cs" />
    <Compile Remove="Configurations\20220829100113_addPictureColumnToıTEM.Designer.cs" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.11" />
    <PackageReference Include="NETCore.MailKit" Version="2.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Application\Application.csproj" />
    <ProjectReference Include="..\AuctionSystem.Infrastructure\AuctionSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
